<?php

namespace App\Support;

class PermissionCatalog
{
    /**
     * @return array<int, string>
     */
    public static function all(): array
    {
        return [
            'projects.view',
            'projects.manage',
            'drawings.view',
            'drawings.manage',
            'snags.view',
            'snags.create',
            'snags.update',
            'snags.delete',
            'snags.assign',
            'snags.transition',
            'snags.comment',
            'snags.attach',
            'snags.close.override',
            'automation.view',
            'automation.manage',
            'kanban.view',
            'dashboard.view',
            'closeout.templates.view',
            'closeout.templates.manage',
            'closeout.instances.view',
            'closeout.instances.update',
            'closeout.review',
            'punch_lists.view',
            'punch_lists.manage',
            'commissioning.view',
            'commissioning.manage',
            'commissioning.witness.sign',
            'toc.view',
            'toc.manage',
            'toc.sign',
            'exports.view',
            'exports.request',
            'exports.download',
            'inspections.templates.view',
            'inspections.templates.manage',
            'inspections.recurring.view',
            'inspections.recurring.manage',
            'inspections.submissions.view',
            'inspections.submissions.create',
            'inspections.submissions.update',
            'inspections.submissions.submit',
            'inspections.approvals.review',
            'inspections.signatures.sign',
            'inspections.requests.view',
            'inspections.requests.manage',
            'inspections.reports.view',
            'inspections.reports.export',
            'equipment.view',
            'equipment.manage',
            'equipment.maintenance.log',
            'notification.preferences.manage',
            'mobile.sync',
            'notifications.view',
            'onboarding.update',
            // Multi-party handover workflow verbs (BRD §6.3 / §10 action matrix).
            'handover.view',
            'handover.create',
            'handover.submit',
            'handover.comment',
            'handover.forward',
            'handover.return',
            'handover.revise',
            'handover.approve',
            'handover.consolidate',
            'handover.assign',
            'handover.close',
            'handover.cancel',
            'workflow.configure',
            'areas.manage',
            'categories.manage',
            'audit.view',
            'audit.export',
            'ops.feature_flags.manage',
            'ops.usage_limits.manage',
            'ops.security.manage',
            'ops.health.view',
            'ops.support.manage',
        ];
    }

    /**
     * @return array<string, array<int, string>>
     */
    public static function roleMap(): array
    {
        return [
            'org_admin' => self::all(),
            'owner' => self::all(),
            'consultant' => [
                'projects.view',
                'drawings.view',
                'drawings.manage',
                'snags.view',
                'snags.create',
                'snags.update',
                'snags.assign',
                'snags.transition',
                'snags.comment',
                'snags.attach',
                'automation.view',
                'automation.manage',
                'kanban.view',
                'dashboard.view',
                'closeout.templates.view',
                'closeout.instances.view',
                'closeout.instances.update',
                'closeout.review',
                'punch_lists.view',
                'punch_lists.manage',
                'commissioning.view',
                'commissioning.manage',
                'commissioning.witness.sign',
                'toc.view',
                'toc.manage',
                'toc.sign',
                'exports.view',
                'exports.request',
                'exports.download',
                'inspections.templates.view',
                'inspections.recurring.view',
                'inspections.recurring.manage',
                'inspections.submissions.view',
                'inspections.approvals.review',
                'inspections.signatures.sign',
                'inspections.requests.view',
                'inspections.requests.manage',
                'inspections.reports.view',
                'inspections.reports.export',
                'equipment.view',
                'equipment.maintenance.log',
                'notification.preferences.manage',
                'mobile.sync',
                'notifications.view',
                'onboarding.update',
            ],
            'contractor' => [
                'projects.view',
                'drawings.view',
                'snags.view',
                'snags.create',
                'snags.update',
                'snags.assign',
                'snags.transition',
                'snags.comment',
                'snags.attach',
                'automation.view',
                'kanban.view',
                'dashboard.view',
                'closeout.templates.view',
                'closeout.instances.view',
                'closeout.instances.update',
                'punch_lists.view',
                'commissioning.view',
                'commissioning.witness.sign',
                'toc.view',
                'toc.sign',
                'exports.view',
                'exports.request',
                'exports.download',
                'inspections.templates.view',
                'inspections.recurring.view',
                'inspections.submissions.view',
                'inspections.submissions.create',
                'inspections.submissions.update',
                'inspections.submissions.submit',
                'inspections.signatures.sign',
                'inspections.requests.view',
                'inspections.requests.manage',
                'inspections.reports.view',
                'inspections.reports.export',
                'equipment.view',
                'equipment.manage',
                'equipment.maintenance.log',
                'notification.preferences.manage',
                'mobile.sync',
                'notifications.view',
                'onboarding.update',
            ],
            'project_manager' => [
                'projects.view',
                'projects.manage',
                'drawings.view',
                'drawings.manage',
                'snags.view',
                'snags.create',
                'snags.update',
                'snags.assign',
                'snags.transition',
                'snags.comment',
                'snags.attach',
                'automation.view',
                'automation.manage',
                'kanban.view',
                'dashboard.view',
                'closeout.templates.view',
                'closeout.templates.manage',
                'closeout.instances.view',
                'closeout.instances.update',
                'closeout.review',
                'punch_lists.view',
                'punch_lists.manage',
                'commissioning.view',
                'commissioning.manage',
                'commissioning.witness.sign',
                'toc.view',
                'toc.manage',
                'toc.sign',
                'exports.view',
                'exports.request',
                'exports.download',
                'inspections.templates.view',
                'inspections.templates.manage',
                'inspections.recurring.view',
                'inspections.recurring.manage',
                'inspections.submissions.view',
                'inspections.submissions.create',
                'inspections.submissions.update',
                'inspections.submissions.submit',
                'inspections.approvals.review',
                'inspections.signatures.sign',
                'inspections.requests.view',
                'inspections.requests.manage',
                'inspections.reports.view',
                'inspections.reports.export',
                'equipment.view',
                'equipment.manage',
                'equipment.maintenance.log',
                'notification.preferences.manage',
                'mobile.sync',
                'notifications.view',
                'onboarding.update',
            ],
            'engineer' => [
                'projects.view',
                'drawings.view',
                'snags.view',
                'snags.create',
                'snags.update',
                'snags.transition',
                'snags.comment',
                'snags.attach',
                'automation.view',
                'kanban.view',
                'dashboard.view',
                'closeout.templates.view',
                'closeout.instances.view',
                'closeout.instances.update',
                'punch_lists.view',
                'commissioning.view',
                'toc.view',
                'exports.view',
                'exports.request',
                'exports.download',
                'inspections.templates.view',
                'inspections.recurring.view',
                'inspections.submissions.view',
                'inspections.submissions.create',
                'inspections.submissions.update',
                'inspections.submissions.submit',
                'inspections.signatures.sign',
                'inspections.requests.view',
                'inspections.requests.manage',
                'inspections.reports.view',
                'inspections.reports.export',
                'equipment.view',
                'equipment.manage',
                'equipment.maintenance.log',
                'notification.preferences.manage',
                'mobile.sync',
                'notifications.view',
                'onboarding.update',
            ],
            'inspector' => [
                'projects.view',
                'drawings.view',
                'snags.view',
                'snags.transition',
                'snags.comment',
                'automation.view',
                'kanban.view',
                'dashboard.view',
                'closeout.templates.view',
                'closeout.instances.view',
                'closeout.instances.update',
                'closeout.review',
                'punch_lists.view',
                'commissioning.view',
                'commissioning.witness.sign',
                'toc.view',
                'toc.sign',
                'exports.view',
                'exports.download',
                'inspections.templates.view',
                'inspections.recurring.view',
                'inspections.submissions.view',
                'inspections.approvals.review',
                'inspections.signatures.sign',
                'inspections.requests.view',
                'inspections.requests.manage',
                'inspections.reports.view',
                'inspections.reports.export',
                'equipment.view',
                'equipment.maintenance.log',
                'notification.preferences.manage',
                'mobile.sync',
                'notifications.view',
                'onboarding.update',
            ],
            'viewer' => [
                'projects.view',
                'drawings.view',
                'snags.view',
                'automation.view',
                'kanban.view',
                'dashboard.view',
                'punch_lists.view',
                'commissioning.view',
                'toc.view',
                'exports.view',
                'inspections.templates.view',
                'inspections.recurring.view',
                'inspections.submissions.view',
                'inspections.requests.view',
                'inspections.reports.view',
                'equipment.view',
                'notifications.view',
            ],

            // ── BRD multi-party handover roles (Phase 1 · Workstream C, §10 matrix) ──
            // Admin: configuration only, separated from business transactions (§10.1).
            'system_administrator' => [
                'projects.view', 'projects.manage',
                'drawings.view', 'drawings.manage',
                'snags.view', 'kanban.view', 'dashboard.view',
                'automation.view', 'automation.manage',
                'workflow.configure', 'areas.manage', 'categories.manage',
                'closeout.templates.view', 'closeout.templates.manage',
                'inspections.templates.view', 'inspections.templates.manage',
                'inspections.recurring.view', 'inspections.recurring.manage',
                'inspections.submissions.view', 'inspections.requests.view',
                'inspections.reports.view', 'inspections.reports.export',
                'equipment.view',
                'exports.view', 'exports.request', 'exports.download',
                'handover.view', 'audit.view', 'audit.export',
                'notification.preferences.manage', 'notifications.view',
                'mobile.sync', 'onboarding.update',
                'ops.feature_flags.manage', 'ops.usage_limits.manage', 'ops.security.manage', 'ops.health.view', 'ops.support.manage',
            ],
            // ZAIDG — submit, respond to snags, add evidence, resubmit.
            'contractor_submitter' => [
                'projects.view', 'drawings.view',
                'snags.view', 'snags.create', 'snags.update', 'snags.transition', 'snags.comment', 'snags.attach',
                'kanban.view', 'dashboard.view',
                'handover.view', 'handover.create', 'handover.submit', 'handover.comment', 'handover.forward', 'handover.cancel',
                'closeout.instances.view', 'closeout.instances.update',
                'inspections.submissions.view', 'inspections.submissions.create', 'inspections.submissions.update', 'inspections.submissions.submit', 'inspections.signatures.sign',
                'exports.view', 'exports.request', 'exports.download',
                'equipment.view',
                'notification.preferences.manage', 'notifications.view', 'mobile.sync', 'onboarding.update',
            ],
            // DAR — review documents, create/manage the construction snag list, comment, return, forward.
            'consultant_reviewer' => [
                'projects.view', 'drawings.view', 'drawings.manage',
                'snags.view', 'snags.create', 'snags.update', 'snags.assign', 'snags.transition', 'snags.comment', 'snags.attach',
                'kanban.view', 'dashboard.view',
                'handover.view', 'handover.comment', 'handover.return', 'handover.revise', 'handover.forward',
                'closeout.review', 'closeout.instances.view',
                'inspections.submissions.view', 'inspections.approvals.review', 'inspections.requests.view', 'inspections.requests.manage', 'inspections.reports.view', 'inspections.reports.export',
                'exports.view', 'exports.request', 'exports.download',
                'equipment.view',
                'notification.preferences.manage', 'notifications.view', 'mobile.sync', 'onboarding.update',
            ],
            // Amana — authority review, comment, return/reject, forward.
            'authority_reviewer' => [
                'projects.view', 'drawings.view',
                'snags.view', 'snags.comment',
                'kanban.view', 'dashboard.view',
                'handover.view', 'handover.comment', 'handover.return', 'handover.approve', 'handover.forward',
                'exports.view', 'exports.download',
                'notifications.view', 'notification.preferences.manage', 'onboarding.update',
            ],
            // Advanced Gardens — owner review, comment, revise, return/reject, approve, forward, close.
            'owner_reviewer' => [
                'projects.view', 'drawings.view',
                'snags.view', 'snags.comment',
                'kanban.view', 'dashboard.view',
                'handover.view', 'handover.comment', 'handover.return', 'handover.revise', 'handover.approve', 'handover.forward', 'handover.close', 'handover.cancel',
                'exports.view', 'exports.request', 'exports.download',
                'notifications.view', 'notification.preferences.manage', 'onboarding.update',
            ],
            // Morganti FMMP — assign inspections, add observations, consolidate, revise, approve/recommend.
            'fmmp_coordinator' => [
                'projects.view', 'drawings.view',
                'snags.view', 'snags.create', 'snags.update', 'snags.assign', 'snags.comment', 'snags.attach',
                'kanban.view', 'dashboard.view',
                'handover.view', 'handover.comment', 'handover.return', 'handover.revise', 'handover.approve', 'handover.forward', 'handover.consolidate', 'handover.assign', 'handover.cancel',
                'inspections.templates.view', 'inspections.recurring.view', 'inspections.submissions.view', 'inspections.approvals.review', 'inspections.requests.view', 'inspections.requests.manage', 'inspections.reports.view', 'inspections.reports.export',
                'exports.view', 'exports.request', 'exports.download',
                'equipment.view',
                'notification.preferences.manage', 'notifications.view', 'mobile.sync', 'onboarding.update',
            ],
            // JASH / Initial — perform assigned inspections, upload photos, raise operational snags.
            'service_provider_inspector' => [
                'projects.view', 'drawings.view',
                'snags.view', 'snags.create', 'snags.comment', 'snags.attach', 'snags.transition',
                'kanban.view', 'dashboard.view',
                'handover.view', 'handover.comment', 'handover.forward',
                'inspections.templates.view', 'inspections.submissions.view', 'inspections.submissions.create', 'inspections.submissions.update', 'inspections.submissions.submit', 'inspections.signatures.sign', 'inspections.requests.view', 'inspections.reports.view',
                'equipment.view',
                'notification.preferences.manage', 'notifications.view', 'mobile.sync', 'onboarding.update',
            ],
            // Read-only auditor — view authorized records and the audit trail; no transactions (§10).
            'auditor' => [
                'projects.view', 'drawings.view', 'snags.view',
                'kanban.view', 'dashboard.view',
                'handover.view',
                'punch_lists.view', 'commissioning.view', 'toc.view',
                'exports.view',
                'inspections.templates.view', 'inspections.recurring.view', 'inspections.submissions.view', 'inspections.requests.view', 'inspections.reports.view',
                'equipment.view',
                'audit.view', 'audit.export',
                'notifications.view',
            ],
        ];
    }
}

